name = "amber"
version = "0.2.0"
description = "Deno bindings for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "han-tyumi", repo = "amber" }

target = "javascript"

[javascript]
runtime = "deno"
typescript_declarations = true

[javascript.deno]
allow_read = true
allow_write = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
