import * as $signal from "$/amber/amber/deno/signal.mjs";
import {
  fromEnumCustomType,
  toEnumCustomType,
} from "~/utils/enumCustomType.ts";

// TODO(@han-tyumi): Need to use better naming for Gleam/JS type conversion functions.
// Maybe a `$` to signify Gleam?
export const toSignalType = toEnumCustomType<
  Deno.Signal,
  $signal.Signal$
>({
  SIGABRT: $signal.Signal$SIGABRT,
  SIGALRM: $signal.Signal$SIGALRM,
  SIGBREAK: $signal.Signal$SIGBREAK,
  SIGBUS: $signal.Signal$SIGBUS,
  SIGCHLD: $signal.Signal$SIGCHLD,
  SIGCONT: $signal.Signal$SIGCONT,
  SIGEMT: $signal.Signal$SIGEMT,
  SIGFPE: $signal.Signal$SIGFPE,
  SIGHUP: $signal.Signal$SIGHUP,
  SIGILL: $signal.Signal$SIGILL,
  SIGINFO: $signal.Signal$SIGINFO,
  SIGINT: $signal.Signal$SIGINT,
  SIGIO: $signal.Signal$SIGIO,
  SIGPOLL: $signal.Signal$SIGPOLL,
  SIGUNUSED: $signal.Signal$SIGUNUSED,
  SIGKILL: $signal.Signal$SIGKILL,
  SIGPIPE: $signal.Signal$SIGPIPE,
  SIGPROF: $signal.Signal$SIGPROF,
  SIGPWR: $signal.Signal$SIGPWR,
  SIGQUIT: $signal.Signal$SIGQUIT,
  SIGSEGV: $signal.Signal$SIGSEGV,
  SIGSTKFLT: $signal.Signal$SIGSTKFLT,
  SIGSTOP: $signal.Signal$SIGSTOP,
  SIGSYS: $signal.Signal$SIGSYS,
  SIGTERM: $signal.Signal$SIGTERM,
  SIGTRAP: $signal.Signal$SIGTRAP,
  SIGTSTP: $signal.Signal$SIGTSTP,
  SIGTTIN: $signal.Signal$SIGTTIN,
  SIGTTOU: $signal.Signal$SIGTTOU,
  SIGURG: $signal.Signal$SIGURG,
  SIGUSR1: $signal.Signal$SIGUSR1,
  SIGUSR2: $signal.Signal$SIGUSR2,
  SIGVTALRM: $signal.Signal$SIGVTALRM,
  SIGWINCH: $signal.Signal$SIGWINCH,
  SIGXCPU: $signal.Signal$SIGXCPU,
  SIGXFSZ: $signal.Signal$SIGXFSZ,
});

export const toSignal = fromEnumCustomType<Deno.Signal>(
  new Map([
    [$signal.SIGABRT, "SIGABRT"],
    [$signal.SIGALRM, "SIGALRM"],
    [$signal.SIGBREAK, "SIGBREAK"],
    [$signal.SIGBUS, "SIGBUS"],
    [$signal.SIGCHLD, "SIGCHLD"],
    [$signal.SIGCONT, "SIGCONT"],
    [$signal.SIGEMT, "SIGEMT"],
    [$signal.SIGFPE, "SIGFPE"],
    [$signal.SIGHUP, "SIGHUP"],
    [$signal.SIGILL, "SIGILL"],
    [$signal.SIGINFO, "SIGINFO"],
    [$signal.SIGINT, "SIGINT"],
    [$signal.SIGIO, "SIGIO"],
    [$signal.SIGPOLL, "SIGPOLL"],
    [$signal.SIGUNUSED, "SIGUNUSED"],
    [$signal.SIGKILL, "SIGKILL"],
    [$signal.SIGPIPE, "SIGPIPE"],
    [$signal.SIGPROF, "SIGPROF"],
    [$signal.SIGPWR, "SIGPWR"],
    [$signal.SIGQUIT, "SIGQUIT"],
    [$signal.SIGSEGV, "SIGSEGV"],
    [$signal.SIGSTKFLT, "SIGSTKFLT"],
    [$signal.SIGSTOP, "SIGSTOP"],
    [$signal.SIGSYS, "SIGSYS"],
    [$signal.SIGTERM, "SIGTERM"],
    [$signal.SIGTRAP, "SIGTRAP"],
    [$signal.SIGTSTP, "SIGTSTP"],
    [$signal.SIGTTIN, "SIGTTIN"],
    [$signal.SIGTTOU, "SIGTTOU"],
    [$signal.SIGURG, "SIGURG"],
    [$signal.SIGUSR1, "SIGUSR1"],
    [$signal.SIGUSR2, "SIGUSR2"],
    [$signal.SIGVTALRM, "SIGVTALRM"],
    [$signal.SIGWINCH, "SIGWINCH"],
    [$signal.SIGXCPU, "SIGXCPU"],
    [$signal.SIGXFSZ, "SIGXFSZ"],
  ]),
);
