import * as $signal from "$/amber/amber/deno/signal.mjs";
import {
  fromEnumCustomType,
  toEnumCustomType,
} from "~/utils/enumCustomType.ts";

// TODO(@han-tyumi): Need to use better naming for Gleam/JS type conversion functions.
// Maybe a `$` to signify Gleam?
export const toSignalType = toEnumCustomType<
  Deno.Signal,
  $signal.Signal$
>({
  SIGABRT: $signal.SIGABRT,
  SIGALRM: $signal.SIGALRM,
  SIGBREAK: $signal.SIGBREAK,
  SIGBUS: $signal.SIGBUS,
  SIGCHLD: $signal.SIGCHLD,
  SIGCONT: $signal.SIGCONT,
  SIGEMT: $signal.SIGEMT,
  SIGFPE: $signal.SIGFPE,
  SIGHUP: $signal.SIGHUP,
  SIGILL: $signal.SIGILL,
  SIGINFO: $signal.SIGINFO,
  SIGINT: $signal.SIGINT,
  SIGIO: $signal.SIGIO,
  SIGPOLL: $signal.SIGPOLL,
  SIGUNUSED: $signal.SIGUNUSED,
  SIGKILL: $signal.SIGKILL,
  SIGPIPE: $signal.SIGPIPE,
  SIGPROF: $signal.SIGPROF,
  SIGPWR: $signal.SIGPWR,
  SIGQUIT: $signal.SIGQUIT,
  SIGSEGV: $signal.SIGSEGV,
  SIGSTKFLT: $signal.SIGSTKFLT,
  SIGSTOP: $signal.SIGSTOP,
  SIGSYS: $signal.SIGSYS,
  SIGTERM: $signal.SIGTERM,
  SIGTRAP: $signal.SIGTRAP,
  SIGTSTP: $signal.SIGTSTP,
  SIGTTIN: $signal.SIGTTIN,
  SIGTTOU: $signal.SIGTTOU,
  SIGURG: $signal.SIGURG,
  SIGUSR1: $signal.SIGUSR1,
  SIGUSR2: $signal.SIGUSR2,
  SIGVTALRM: $signal.SIGVTALRM,
  SIGWINCH: $signal.SIGWINCH,
  SIGXCPU: $signal.SIGXCPU,
  SIGXFSZ: $signal.SIGXFSZ,
});

export const toSignal = fromEnumCustomType<Deno.Signal>(
  new Map([
    [$signal.SIGABRT, "SIGABRT"],
    [$signal.SIGALRM, "SIGALRM"],
    [$signal.SIGBREAK, "SIGBREAK"],
    [$signal.SIGBUS, "SIGBUS"],
    [$signal.SIGCHLD, "SIGCHLD"],
    [$signal.SIGCONT, "SIGCONT"],
    [$signal.SIGEMT, "SIGEMT"],
    [$signal.SIGFPE, "SIGFPE"],
    [$signal.SIGHUP, "SIGHUP"],
    [$signal.SIGILL, "SIGILL"],
    [$signal.SIGINFO, "SIGINFO"],
    [$signal.SIGINT, "SIGINT"],
    [$signal.SIGIO, "SIGIO"],
    [$signal.SIGPOLL, "SIGPOLL"],
    [$signal.SIGUNUSED, "SIGUNUSED"],
    [$signal.SIGKILL, "SIGKILL"],
    [$signal.SIGPIPE, "SIGPIPE"],
    [$signal.SIGPROF, "SIGPROF"],
    [$signal.SIGPWR, "SIGPWR"],
    [$signal.SIGQUIT, "SIGQUIT"],
    [$signal.SIGSEGV, "SIGSEGV"],
    [$signal.SIGSTKFLT, "SIGSTKFLT"],
    [$signal.SIGSTOP, "SIGSTOP"],
    [$signal.SIGSYS, "SIGSYS"],
    [$signal.SIGTERM, "SIGTERM"],
    [$signal.SIGTRAP, "SIGTRAP"],
    [$signal.SIGTSTP, "SIGTSTP"],
    [$signal.SIGTTIN, "SIGTTIN"],
    [$signal.SIGTTOU, "SIGTTOU"],
    [$signal.SIGURG, "SIGURG"],
    [$signal.SIGUSR1, "SIGUSR1"],
    [$signal.SIGUSR2, "SIGUSR2"],
    [$signal.SIGVTALRM, "SIGVTALRM"],
    [$signal.SIGWINCH, "SIGWINCH"],
    [$signal.SIGXCPU, "SIGXCPU"],
    [$signal.SIGXFSZ, "SIGXFSZ"],
  ]),
);
